Удаление Djoser
MikhailDevW/DecksCard pull request #6
Opened 2023-06-08 16:45 UTC by MikhailDevW

Удаление джосера и иные мелкие правки.

2023-06-08 18:18 UTC, HstrPrn requested changes

2023-06-08 18:18 UTC, HstrPrn commented on backend/decksapi/decksapi/settings.py
> -# }
ну слава богу, эти твои комменты глаза мазолят)

2023-06-08 18:18 UTC, HstrPrn commented on backend/decksapi/requirements.txt
> -djoser==2.1.0
прваильно, настоящий програмизд все пишет сам!

2023-06-08 18:18 UTC, HstrPrn commented on backend/decksapi/decksapi/settings.py
> +    'rest_framework_simplejwt',
зачем ты регаешь симпл дживитимпл?

2023-06-08 18:20 UTC, MikhailDevW commented on backend/decksapi/decksapi/settings.py
> -# }
Аахахаха

2023-06-08 18:20 UTC, MikhailDevW commented on backend/decksapi/decksapi/settings.py
> -# }
Блин, орнул

2023-06-08 18:58 UTC, MikhailDevW commented on backend/decksapi/decksapi/settings.py
> +    'rest_framework_simplejwt',
If you wish to use localizations/translations, simply add rest_framework_simplejwt to INSTALLED_APPS.

2023-06-09 15:12 UTC, HstrPrn commented on backend/decksapi/api/mixins.py
> +class CreateViewSet(
from rest_framework.generics import CreateAPIView и не нужно придумывать велосипед)

2023-06-09 15:19 UTC, HstrPrn commented on backend/decksapi/api/serializers.py
> +    def get_token(cls, user):
зачем оборачивать функцию в функцию, которая просто возвращает оборачиваемую функцию)

2023-06-09 15:29 UTC, HstrPrn commented on backend/decksapi/api/views.py
> +            )
у тебя в конструкторе класса Mail есть обязательный параметр code, но ты его здесь не передаешь.
разве так будет работать?

2023-06-09 15:35 UTC, HstrPrn commented on backend/decksapi/core/models.py
> +        default='user',
если сделать класс RoleChoice(models.TextChoise) то можно будет не хардкодить, и выглядить будет скиллово))

2023-06-09 15:39 UTC, HstrPrn commented on backend/decksapi/core/models.py
> +    REQUIRED_FIELDS = ["first_name", ]
может лучше еще и пароль сделать обязательным?
если я при регистрации, не введя пароль, случайно нажму ентер, то мой юзернейм уже будет занят, а войти в него я не смогу

2023-06-09 15:39 UTC, HstrPrn commented on backend/decksapi/decksapi/settings.py
> +        'NAME': BASE_DIR / env('DB_NAME'),
отличный способ!))

2023-06-09 15:41 UTC, HstrPrn commented on backend/decksapi/core/utils.py
> +    def __init__(self, to, code) -> None:
или здесь поле code сделать необязательным, добавив дефолтное значение

2023-06-09 15:44 UTC, HstrPrn commented on backend/decksapi/decksapi/settings.py
> +    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
насколь я понял, тут почти все отстается по дефолту. зачем тогда писать сюда дефолтные значения?

2023-06-09 16:38 UTC, MikhailDevW commented on backend/decksapi/api/serializers.py
> +
Нене, связь с моделью я хочу оставить раз такое даётся под капотом и оно само там рулит.

2023-06-09 16:40 UTC, MikhailDevW commented on backend/decksapi/api/serializers.py
> +from rest_framework_simplejwt.tokens import RefreshToken
Посмотрим. Исправим.

2023-06-09 16:41 UTC, MikhailDevW commented on backend/decksapi/api/serializers.py
> +    def get_token(cls, user):
Вот тут не понял.

2023-06-09 16:41 UTC, MikhailDevW commented on backend/decksapi/api/views.py
> +            )
Да, надо доделать, исправим

2023-06-09 16:42 UTC, MikhailDevW commented on backend/decksapi/core/models.py
> +        default='user',
Опа... А это кто? Посмотрим

2023-06-09 16:44 UTC, MikhailDevW commented on backend/decksapi/decksapi/settings.py
> +    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
Нууууу у я экскрементировал. В принципе можно и убрать да. Хотя в доке они пишут вообще все настройки. Видимо чтоб перед глазами были. Да надо либо убрать либо все лепить.

2023-06-11 20:41 UTC, HstrPrn approved these changes
по моему все норм

2023-06-11 20:44 UTC, merged